# Generated by Django 2.2.6 on 2020-01-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200107_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(blank=True),
        ),
    ]
